### ISSUE TITLE
NCPF structure redesign

### ISSUE THREAD

**Issue by ThizThizzyDizzy** [ThizThizzyDizzy/nc-reactor-generator#123]
NCPF configuration sections all resemble the messy internals of the plannerator; while very useful for it, it's not helpful for anything else, and doesn't mirror the game very well.
For instance, Overhaul SFR blocks can be set to be heatsinks and moderators; perhaps this should follow NC more strictly?

**Comment by thedeadferryman** [comment]
The idea to separate block definitions and block usages as it is done now is great. But block definitions are stored in a quite weird way now (ports, oh my god, how the ports are defined...). It would be really great if block definitions were all stored in a single place, so it would be just about to collect one array from the data.

**Comment by ThizThizzyDizzy** [comment]
Yeahh the ports (and casings) were added after-the-fact, generated from their parent block in the plannerator based on if it has recipes or not
So, of course, I reflected that in NCPF, creating a mess of a system that's been causing problems ever since. (For instance, addons that use blocks from another addon don't save/load properly because of this. I could never figure out why, and I could fix saving or loading, but not both)

**Comment by ThizThizzyDizzy** [comment]
As for the block definitions, rather than a hardcoded list of options, perhaps a list of capabilities, such that addons could add more, or various software could add special ones if needed

**Comment by thedeadferryman** [comment]
Sure, this seems to be a decent option to make the format more flexible

**Comment by ThizThizzyDizzy** [comment]
This should probably also be extended to configuration settings (like neutron range, min/max size, etc)

**Comment by ThizThizzyDizzy** [comment]
Done, basically everything's a module now
