### ISSUE TITLE
Oredict/tag support

### ISSUE THREAD

**Issue by ThizThizzyDizzy** [ThizThizzyDizzy/nc-reactor-generator#124]
Current NCPF uses ingame block names for compatibility with reactor builders and building gadgets and whatnot
However, some blocks (like graphite moderators) can be any graphite, not just NC graphite
Should this be a formatted string (#tag, ore:ironOre, etc) or have a special structure?

**Comment by CodedSakura** [comment]
retaining parity with minecraft feels like the best approach

**Comment by ThizThizzyDizzy** [comment]
I feel a formatted string is better for simplicity, but the question then rises how things should be defined
For instance:
Normal block/item: `namespace:name:metadata`, or just `namespace:name` if the block has no metadata
Block tag: `#namespace:name` (matches block tag syntax of newer versions)
Those are fairly straightforward, but what about fluids and oredict? I'd like to avoid using prefixes like `fluid:` or `ore:` as those could be confused with namespaces
In current NCPF, fluids have no prefix (so just `water`), but I'd prefer to avoid that
I could use JEI's prefix for oredicts, `$oreIron`

But then what about 1.16/1.19? If oredict/tags are the same, (I don't know if they are, but they seem to be?) Then that separation isn't necessary, but fluids still need to be distinct from items

To add more complication to the fluid issue, buckets of fluids (in 1.12 at least) don't necessarily have their own id at all

**Comment by ThizThizzyDizzy** [comment]
Decided to go with a data structure for this to support more complex things (like blockstates) without needing fancy string parsing

Required types:
- [x] Legacy Block/item (-1.12)
- [x] Legacy fluid (-1.12)
- [x] Oredict (all versions)
- [x] Block/item (1.13+)
- [x] Block/item Tag (1.13+)
- [x] fluid (1.13+)
- [x] fluid tag (1.13+)
- [x] generic (not associated with anything ingame)

Blocks vs items are determined by context
Fluids can be used in either case, denoting either fluid blocks or fluid containers (buckets, appropriately filled tanks, etc)

Custom type support is also required (for instance, QMD particles)
