### ISSUE TITLE
NCPF Turbines

### ISSUE THREAD

**Issue by ThizThizzyDizzy** [ThizThizzyDizzy/nc-reactor-generator#128]
The turbine format in NCPF is rather messy, previously containing just a list of blade types and a list for the coils, and now containing the whole multiblock (for casings) while the majority of the interior is the same
Should turbines have a special format to avoid saving unnecessary information, or should it save the whole interior like every other block for easier integration?

**Comment by ThizThizzyDizzy** [comment]
Perhaps both?
i.e. save total dimensions and every block's location for core NCPF to keep consistency with other multiblocks, but also include a list of blades and bearing size *as a plannerator module* for quick searching

**Comment by secretmeister** [comment]
One thing I was thinking about for turbines is maybe an easy mode, because it can get annoying to manually place in each ring of baldes, so you can just set the size of the core, and then quickly switch between blade types for an entire ring, but make coil placing the same as usual

**Comment by ThizThizzyDizzy** [comment]
This is planned for when I rewrite the planner for the turbine again; if you look at the versions before casings were added, it was actually like this; (one cell for each blade, then just the coils, one click to set bearing size)
When I added casings, I had to expand it to cover the walls of the reactor, and never expanded the fancy interactions to match it (i.e. placing a whole blade ring at once, or changing bearing/shaft size with a single click rather than manually replacing the blocks)

**Comment by ThizThizzyDizzy** [comment]
(I've split that into #129 to keep it separate from the NCPF discussion)

**Comment by ThizThizzyDizzy** [comment]
Full interior is saved just like any other multiblock
