### ISSUE TITLE
PNG Export broken in all 2.9 versions

### ISSUE THREAD

**Issue by Thalzamar** [ThizThizzyDizzy/nc-reactor-generator#13]
For some reason it trys to export .png with the size of 0 in all of the 2.9 versions
version 2.8.1 works fine 
v2.9.2 also gave me that error when trying to import the .json i exported 
[Error Sun Jul 26 16-58-21 CEST 2020.log](https://github.com/ThizThizzyDizzy/nc-reactor-generator/files/4977819/Error.Sun.Jul.26.16-58-21.CEST.2020.log)

[testing.zip](https://github.com/ThizThizzyDizzy/nc-reactor-generator/files/4977821/testing.zip)

"test" is the exported .json and "Mix it" is the reactor i used

**Comment by ThizThizzyDizzy** [comment]
Fixed PNG export in v2.9.3

Unable to open zip file; it's marked as invalid
If the .json import error persists, please make a new issue
