### ISSUE TITLE
vr crash

### ISSUE THREAD

**Issue by davidCMs** [ThizThizzyDizzy/nc-reactor-generator#138]
hello i am new to using this maybe i am doing something wrong i am using oculus quest 2 as my head set this is the java err
[hs_err_pid20692.log](https://github.com/ThizThizzyDizzy/nc-reactor-generator/files/12161150/hs_err_pid20692.log)

**Comment by ThizThizzyDizzy** [comment]
(yay a VR user)
Make sure java is up to date?
Beyond that, I'd have to mess with it a bit

**Comment by davidCMs** [comment]
running  it via bat file whit java 8 fixed it also this is a lot of work for a reactor planer thank you just you need to document controls for vr some where
