### ISSUE TITLE
Json export not working in 2.9.3

### ISSUE THREAD

**Issue by Zalgo239** [ThizThizzyDizzy/nc-reactor-generator#14]
When trying to export a reactor in 2.9.3 I get a 0KB json and an error:
[Error Mon Jul 27 11-06-40 CEST 2020.log](https://github.com/ThizThizzyDizzy/nc-reactor-generator/files/4981051/Error.Mon.Jul.27.11-06-40.CEST.2020.log)

**Comment by ThizThizzyDizzy** [comment]
It looks like you’re trying to export an MSR to the Hellrage format.
It can’t export MSRs to hellrage format because the hellrage planner doesn’t properly support MSRs

I’ll mark this as an enhancement though

**Comment by ThizThizzyDizzy** [comment]
I've decided not to add hellrage JSON support for MSRs (due to lack of support in Hellrage planner), but instead I'll mark this as a bug since it crashes rather than properly handling the error :P
