### ISSUE TITLE
'casing incomplete' when casing is not incomplete

### ISSUE THREAD

**Issue by ThizThizzyDizzy** [ThizThizzyDizzy/nc-reactor-generator#158]
happens on newly created reactors

**Comment by QuantumTraverse** [comment]
Perhaps related to this is the fact that the plannerator won't let me place output vents at all

**Comment by ThizThizzyDizzy** [comment]
something I noticed while debugging other things: output vents can only be placed within the reactor, causing them to be invalid in the casings.
