### ISSUE TITLE
[Overhaul Turbine] Caught exception processing input when placing a Stator.

### ISSUE THREAD

**Issue by justwlocke** [ThizThizzyDizzy/nc-reactor-generator#169]
Planner Version: NC-Reactor-Plannerator-5.0.0-beta.5

Default Nuclearcraft config

Not entirely sure how to title this one, but I was making a turbine, 5x5x6 (5 tall, 5 deep, 6 wide), and had the rotor bearing, shaft, and all blades placed (all extreme alloy). However, the expansion was showing as bad, so I went to put a stator in to see what would happen, and as I placed the last piece, I got a mouse related error.

I was able to save the entire planner file, and it produces that same error every time you open the Turbine (as well as a second one).
[ErroringTurbine.ncpf.json](https://github.com/user-attachments/files/16117551/ErroringTurbine.ncpf.json)

And just in case you _don't_ get the error, here's a pic
![image](https://github.com/ThizThizzyDizzy/nc-reactor-generator/assets/84145548/1b356af7-cc10-4ac8-9979-d6b022454b2b)

as well as the crash report
[crash-Sat Jul 06 17-43-33 CDT 2024.txt](https://github.com/user-attachments/files/16117553/crash-Sat.Jul.06.17-43-33.CDT.2024.txt)

Steps to Reproduce
1. Open the Planner
2. Download my .ncpf file
3. Load it into your planner
4. Open the Turbine
5. Error.

**Comment by Thalzamar** [comment]
it's actually completing the turbine that crashes the turbine
![grafik](https://github.com/ThizThizzyDizzy/nc-reactor-generator/assets/48890032/40799dc0-84bb-40f4-9ee6-f13930cb69eb)

**Comment by ThizThizzyDizzy** [comment]
This was fixed in f39f7b6
