### ISSUE TITLE
Missing Additional Steam Production

### ISSUE THREAD

**Issue by QuantumTraverse** [ThizThizzyDizzy/nc-reactor-generator#22]
Neutron shields actually produce steam at their efficiency. Their useful heat is defined as heat per flux * neutron flux * shield efficiency. Tom apparently forgot to mention this before.

**Comment by ThizThizzyDizzy** [comment]
is shield efficiency the same as its moderator efficiency, or could they be two different values?

**Comment by QuantumTraverse** [comment]
Yes, it is its moderator efficiency value, which is 50% for the default Boron-Silver Neutron Shields, and 100% for QMD's special Hf Shields.

**Comment by ThizThizzyDizzy** [comment]
Do they provide any efficiency? (ex. for MSRs)

**Comment by QuantumTraverse** [comment]
I don't quite understand what you mean by that question.
My best guess is that you are wondering about a pure shield and/or coolant heater moderator line. In that case, the shield will contribute no steam, since it has 0 flux passing through it. If that's not the question you're asking, I probably don't know the answer. It might be better to ask Tom on the specifics of the reactor mechanics.

**Comment by QuantumTraverse** [comment]
I thought about it some more and I think I have a better guess at what you mean now. The shields result in additional heat production for the MSR, making more coolant need to be heated, without any increase in efficiency. The presence of the shields results in eventually more steam output, since one needs to cool the additional heat produced by the shields. Thus, I believe your calculations on the MSRs are fine and correct.

**Comment by ThizThizzyDizzy** [comment]
Alright, thanks :D
