### ISSUE TITLE
Shield-only moderator lines

### ISSUE THREAD

**Issue by QuantumTraverse** [ThizThizzyDizzy/nc-reactor-generator#23]
The planner does not seem to consider than a moderator line can be made entirely of neutron shields, resulting in an increased heat multiplier, but no additional efficiency (since the line has 0 flux). This functionality is part of the way the reactors do work in-game.

**Comment by ThizThizzyDizzy** [comment]
looks like it's specifically set to not form shield-only moderator lines
That looks like an easy fix :P
