### ISSUE TITLE
Suggestion: Group together similar clusters

### ISSUE THREAD

**Issue by Thalzamar** [ThizThizzyDizzy/nc-reactor-generator#25]
![poweredirradiator](https://user-images.githubusercontent.com/48890032/103268006-05c98a80-49b3-11eb-80a8-e0728d013263.png)

see image above , while the irradiators have casing connections they still form clusters with 0 Heat and 0 Flux 
maybe group as X Irradiators Clusters or so
ncpf file for it
[Poweredirradiator.zip](https://github.com/ThizThizzyDizzy/nc-reactor-generator/files/5749953/Poweredirradiator.zip)

**Comment by ThizThizzyDizzy** [comment]
The irradiators will still form clusters, but I agree that they need to be grouped together in the tooltip
