### ISSUE TITLE
Cannot open reactor.json from leu-235.com

### ISSUE THREAD

**Issue by BondarenkoArtur** [ThizThizzyDizzy/nc-reactor-generator#28]
I've generated reactor on https://leu-235.com/ and I want to make some changes.  
But it seems I cannot load json file provided by it.
[Reactor planner](https://github.com/hellrage/NC-Reactor-Planner/releases/tag/v1.2.25) works with this files and if I load file by it and then overwriting json, it loads fine in your reactor-generator program.

**Comment by ThizThizzyDizzy** [comment]
This is because leu-235.com doesn't save the fuel name, which is required by my planner when loading the JSON.
I could make a workaround by searching for the fuel based on fuel stats though.
(When opening it in hellrage's planner, note how the fuel selection box is empty)

**Comment by BondarenkoArtur** [comment]
I'm using their website as they have better generators than your software. Even if it's single-threaded it gives better results usually.
But in other stuff, they are worse. 
I'm generating some generator on the website, then importing into your software and using a generator with one working multiblock and big timeout to improve if it's possible, as your algorithm has multiple priorities and their only specific. 
And yeah, it would be amazing if generator settings would not reset each time I move back and forth between pages.
