### ISSUE TITLE
No multiblocks show up

### ISSUE THREAD

**Issue by Lach01298** [ThizThizzyDizzy/nc-reactor-generator#29]
![image](https://user-images.githubusercontent.com/8176057/113641640-673f7a80-96c1-11eb-983c-14b4aeeda7e5.png)
Clicking add a new multiblock shows an empty display with only a cancel button.
Version:2.18.2

**Comment by ThizThizzyDizzy** [comment]
That's an issue with how it loads modules from previous versions;
Go to settings -> modules and enable underhaul/overhaul modules and they'll show up again

**Comment by Lach01298** [comment]
well i did a clean install now it works. Seems to be a problem updating
