### ISSUE TITLE
Cooling Rate of Coolant Heaters in overhaul MSRs are not shown in the tooltips

### ISSUE THREAD

**Issue by joendter** [ThizThizzyDizzy/nc-reactor-generator#31]
While designing a reactor it is always helpful to not only being able to check placement rules, but also cooling rates quickly, especially for not as experienced players. Right now you have to click at a coolant heater to show the coolant recipe, where you can see the cooling rate. This is probably, because of the possibility that one coolant heater has multiple recipes. But in Vanilla NC:O each coolant heater has only one recipe, so it would be convenient if the cooling rate of the default recipe was shown in the tooltip.
![image](https://user-images.githubusercontent.com/71767955/115149566-00c53f80-a065-11eb-9a1d-c91adc395494.png)
![image](https://user-images.githubusercontent.com/71767955/115149577-10448880-a065-11eb-87f5-05d4063901f7.png)
You also have to try to change the recipe to see its tooltip which is even more inconvenient.

**Comment by ThizThizzyDizzy** [comment]
Added in v3.0.4
