### ISSUE TITLE
[SUGGESTION] Add favourites to block selection

### ISSUE THREAD

**Issue by joendter** [ThizThizzyDizzy/nc-reactor-generator#32]
By default you always have all possible blocks in a certain order. But you don't need all blocks equally often, for example I'm lazy and just let the planner do all the casing stuff for me. So I don't need all the casing blocks at the top of the blocklist. I would like, if you could have a section "favourites" or "bookmark" on the top of the list. There you could put blocks you often use, like cells (maybe even with preset fuel) and moderators and arrange them as you want, depending on how often you need them. You could also use this feature to just put all the stuff used in the casing, and usually done automatically to the bottom of your blocklist.

**Comment by ThizThizzyDizzy** [comment]
The search was supposed to help with this, but it doesn't work as well as I hoped :P
I could add regex functionality to do that, but it probably wouldn't be very user-friendly

**Comment by ThizThizzyDizzy** [comment]
Added exclusion via -excludedstring or -"excluded string" and regex functionality via regex:<regex>
ports are also excluded by default when auto-build casing is on
I'm closing this because I think this is sufficient; Go ahead and reopen the issue if you still want a favorites panel :P
