### ISSUE TITLE
repeatable NPE on main thread

### ISSUE THREAD

**Issue by h4ilst0rm** [ThizThizzyDizzy/nc-reactor-generator#35]
Plannerator 3.0.5 crashes consistently when shift clicking the marked block to place a neutron source.

![image](https://user-images.githubusercontent.com/59488828/115518986-744b9480-a291-11eb-9dee-a4cbfc187e39.png)

2nd reactor (the MSR) in this autosave
[autosave.zip](https://github.com/ThizThizzyDizzy/nc-reactor-generator/files/6349123/autosave.zip)

**Comment by h4ilst0rm** [comment]
Welp, just realized I was trying to place the source in a invalid position, shouldn't still crash though.

**Comment by ThizThizzyDizzy** [comment]
Fixed in v3.0.6
