### ISSUE TITLE
IndexOutOfBounds when copy pasting

### ISSUE THREAD

**Issue by h4ilst0rm** [ThizThizzyDizzy/nc-reactor-generator#36]
I pasted a reactor chunk so it overlapped the casing a bit.
![image](https://user-images.githubusercontent.com/59488828/115765558-99362980-a3af-11eb-9aea-cacb8654c36a.png)
Preview from autosave works and shows the offending pieces in place of casings, but planner crashes when trying to edit the reactor.
![image](https://user-images.githubusercontent.com/59488828/115765863-f29e5880-a3af-11eb-94b6-90e279c65d06.png)
[autosave5.zip](https://github.com/ThizThizzyDizzy/nc-reactor-generator/files/6360463/autosave5.zip)

**Comment by ThizThizzyDizzy** [comment]
Oof, I thought I fixed all the paste issues
Which paste tool were you using? (Move tool with Ctrl, or Ctrl+c/x/v)

**Comment by h4ilst0rm** [comment]
Ctrl+c/x/v

**Comment by ThizThizzyDizzy** [comment]
[autosave5_fixed.zip](https://github.com/ThizThizzyDizzy/nc-reactor-generator/files/6366185/autosave5_fixed.zip)
File recovered ^

**Comment by ThizThizzyDizzy** [comment]
Fixed in v3.0.6
