### ISSUE TITLE
-Port removes Graphite from List

### ISSUE THREAD

**Issue by Thalzamar** [ThizThizzyDizzy/nc-reactor-generator#37]
![grafik](https://user-images.githubusercontent.com/48890032/115884932-b589a300-a44f-11eb-8935-a20fb0772c96.png)

with the default -port filter , graphite is for some reason removed from the list too

**Comment by ThizThizzyDizzy** [comment]
Already fixed in the dev build
Gra**p**hite m**o**de**r**a**t**or
exclusions won't be so lenient; it will require the characters to be next to each other :P

**Comment by ThizThizzyDizzy** [comment]
Fixed in v3.0.6
