### ISSUE TITLE
MSR Feature: Shield as active Moderator needs to be removed

### ISSUE THREAD

**Issue by Thalzamar** [ThizThizzyDizzy/nc-reactor-generator#39]
https://discord.com/channels/425461908712325130/425529560856002561/835242240451936300

Shields as active moderators were removed
it's still in seen here:
enderium enar shield should not work
https://discord.com/channels/425461908712325130/425529560856002561/835240668845572126

**Comment by ThizThizzyDizzy** [comment]
Fixed in v3.0.6
