### ISSUE TITLE
Cannot load reactors with Moar Reactor Functionality blocks.

### ISSUE THREAD

**Issue by CassandraRC7** [ThizThizzyDizzy/nc-reactor-generator#40]
The plannerator can't open any reactors that use Moar Reactor Functionality blocks, possibly Pu-238 schmeared beryllium. The attached errors occur when it is tried with the attached .ncpf file.
[New WinRAR ZIP archive.zip](https://github.com/ThizThizzyDizzy/nc-reactor-generator/files/6382396/New.WinRAR.ZIP.archive.zip)

**Comment by ThizThizzyDizzy** [comment]
Fixed in v3.0.8
