### ISSUE TITLE
Crash after zooming in and out

### ISSUE THREAD

**Issue by DaComputerNerd717** [ThizThizzyDizzy/nc-reactor-generator#41]
So, a list of what I had done so far:
I had opened the planner, tried to open a design, but not had the addons for it (the first exception in the log), added the addons in the configuration, loaded the project, zoomed out, and zoomed back in, and it errored again (the second). Despite being a CME, hitting Ignore caused the planner to fully close.

[Error Wed Apr 28 17-15-05 EDT 2021.log](https://github.com/ThizThizzyDizzy/nc-reactor-generator/files/6394870/Error.Wed.Apr.28.17-15-05.EDT.2021.log)

**Comment by ThizThizzyDizzy** [comment]
Simple synchronization fix stops the CME, but I haven't been able to reproduce the issue of hitting ignore causing the planner to close

**Comment by ThizThizzyDizzy** [comment]
Fixed in v3.1
