### ISSUE TITLE
MSR Grouping / Clusters are broken

### ISSUE THREAD

**Issue by Thalzamar** [ThizThizzyDizzy/nc-reactor-generator#43]
it seems with update 3.0.6 something broke in the MSR logic
![grafik](https://user-images.githubusercontent.com/48890032/116823582-9b557080-ab85-11eb-9ddc-ee48ecc18f79.png)
it can't find the casing anymore and has problems with grouping things together
[pls_halp.zip](https://github.com/ThizThizzyDizzy/nc-reactor-generator/files/6412029/pls_halp.zip)
attached is the design from fuzzy who found the issue and was confused why nothing was working correctly

**Comment by ThizThizzyDizzy** [comment]
That looks like it could very easily be an extra (or missing) `!` :P

**Comment by ThizThizzyDizzy** [comment]
Fixed in v3.1
