### ISSUE TITLE
Add a timeout for suggestor calculations

### ISSUE THREAD

**Issue by h4ilst0rm** [ThizThizzyDizzy/nc-reactor-generator#45]
I was using various suggestors and something was left running in the background after turning it off.
Memory usage did not increase over time, but CPU usage remained very high even after exiting the planner view back to the menu.

![image](https://user-images.githubusercontent.com/59488828/117262662-2d959700-ae5a-11eb-9f7d-31e72df475f8.png)

![image](https://user-images.githubusercontent.com/59488828/117262780-4c942900-ae5a-11eb-8a87-e20082fcf495.png)

**Comment by ThizThizzyDizzy** [comment]
Fixed in v3.2
