### ISSUE TITLE
Suggestion: Hotkey/button for Fluxoverlay

### ISSUE THREAD

**Issue by Thalzamar** [ThizThizzyDizzy/nc-reactor-generator#47]
a hotkey/button that brings up the fluxline overlay from the step by step validation
maybe with a mention in the tutorial section

**Comment by ThizThizzyDizzy** [comment]
Hmm, there's a little problem though
Which flux overlay should be displayed? There's the initial flux propogation, then one or more repropogations if some cells turn off
I could do the last repropogation, which would be the most accurate to the final state of the reactor, but then cells that aren't active wouldn't show any flux propogation at all.
I could do the initial propogation, but then you'd have inactive cells showing a full flux amount
(One of these already kinda happens with the tooltips, but that's a little hidden)

**Comment by Thalzamar** [comment]
sorry i haven't noticed you needed more info(you could have asked in discord you know) >.<
i think the flux you currently have calculated for when the reactor would be turned on 
it might help people to have a visualisation of the individual flux lines to understand how flux propagates through the reactor

**Comment by ThizThizzyDizzy** [comment]
> i think the flux you currently have calculated for when the reactor would be turned on

Do you mean the final flux propogation?
The problem with that is that flux might not seem to update at all until a cell becomes active
If I do the initial propogation to show that, then the flux shown won't always match properly with which cells are active

**Comment by Thalzamar** [comment]
in my opinion it should show how the flux shown in the cell tooltip is calculated 
so the final one
