### ISSUE TITLE
Shieldstatus are ignored when validating primed cells

### ISSUE THREAD

**Issue by Thalzamar** [ThizThizzyDizzy/nc-reactor-generator#52]
https://discord.com/channels/425461908712325130/425529560856002561/846728146623004702

basically even if the shield is closed the validator ignores it for Fluxcalculations

**Comment by Thalzamar** [comment]
what happens is that with a new validation the reactor should be handled as freshly turned on with the shield off and not remember anything 
only once the shield has been turned off and the line validated than the 3 other cells should stay on

**Comment by ThizThizzyDizzy** [comment]
Intended behavior;
The final state of the reactor is shown as if the shields were turned off after the reactor started. This is intended to help in designing togglable reactors
