### ISSUE TITLE
Generator doesn't appear to actually do anything

### ISSUE THREAD

**Issue by joshop** [ThizThizzyDizzy/nc-reactor-generator#53]
I feel like I must be doing something wrong, but loading in, creating a new Overhaul SFR, without modifying anything going to Generate, not modifying settings and clicking Generate again causes nothing to happen. The reactor does not change in the slightest, but upon exiting out of the generator it does log a message: "N iterations" for a nonzero N. While the "generation" is happening, all of the subwindows display "No controller", "Missing input vent", "Missing output vent" and all zero values. There's no tutorial on the actual generator as far as I can see, so I could just be doing something obviously wrong.

**Comment by ThizThizzyDizzy** [comment]
There's no fuels selected by default, so it is not able to generate a valid reactor, thus leaving it blank

(I think there's also a second issue in here where the preview window doesn't show the reactors calculated properly)

I've been neglecting the generator for a while; mostly focusing on suggestors. I'll come back to the generator and revamp it at some point to make it much easier to use

**Comment by ThizThizzyDizzy** [comment]
Gonna close this since the overhaul SFR generator does stuff now. (It's still not *great*, but it does stuff)
