### ISSUE TITLE
I can't start it

### ISSUE THREAD

**Issue by zhangaoyu-me** [ThizThizzyDizzy/nc-reactor-generator#54]

**Comment by zhangaoyu-me** [comment]
I set up all the LIBS correctly, but I didn't respond after double clicking``

**Comment by zhangaoyu-me** [comment]
> I set up all the LIBS correctly, but I didn't respond after double clicking
I'm using version 3.2

**Comment by zhangaoyu-me** [comment]
I set up all the LIBS correctly, but I didn't respond after double clicking
I'm using version 3.2

**Comment by ThizThizzyDizzy** [comment]
the planner should download required libraries automatically;
Which OS are you running it on?

also, in the command prompt (or your OS's equivalent) try `java -jar "path/to/jarfile.jar"`

**Comment by zhangaoyu-me** [comment]
> the planner should download required libraries automatically;
> Which OS are you running it on?
> 
> also, in the command prompt (or your OS's equivalent) try `java -jar "path/to/jarfile.jar"`

I use windows 10 system. I download all the required libraries, but I can't open the program. After clicking, I don't jump out of the download interface like the previous version

**Comment by ThizThizzyDizzy** [comment]
Try running the planner from the command prompt (cmd)

run the command `java -jar "path/to/jarfile.jar"`

**Comment by zhangaoyu-me** [comment]
> Try running the planner from the command prompt (cmd)
> 
> run the command `java -jar "path/to/jarfile.jar"`

The following error will be displayed
Unable to access jarfile path/to/jarfile.jar

**Comment by ThizThizzyDizzy** [comment]
Well yes, you're gonna have to replace `path/to/jarfile.jar` to the actual path to the jarfile
try shift-clicking the jarfile and choosing `Copy as Path`, then pasting that in the console window

**Comment by zhangaoyu-me** [comment]
> 嗯， 是的， 你必须更换到 jarfile
> 的实际路径， 尝试换班点击 jarfile 并选择， 然后粘贴在控制台窗口`path/to/jarfile.jar``Copy as Path`

So how do I change the path

I'm sorry my English is not very good, maybe there are some mistakes, please understand

**Comment by zhangaoyu-me** [comment]
> Well yes, you're gonna have to replace `path/to/jarfile.jar` to the actual path to the jarfile
> try shift-clicking the jarfile and choosing `Copy as Path`, then pasting that in the console window

So how do I change the path

I'm sorry my English is not very good, maybe there are some mistakes, please understand

**Comment by ThizThizzyDizzy** [comment]
1. Shift-right click the NC-Reactor-Generator jarfile
2. Select `Copy as Path`
![image](https://user-images.githubusercontent.com/22590237/121688902-fa19de00-ca91-11eb-908f-03422e8cb60e.png)
3. type `java -jar `in the cmd window
4. press Ctrl+V to paste in the path
5. Press enter

**Comment by zhangaoyu-me** [comment]
> 1. Shift-right click the NC-Reactor-Generator jarfile
> 2. Select `Copy as Path`
>    ![image](https://user-images.githubusercontent.com/22590237/121688902-fa19de00-ca91-11eb-908f-03422e8cb60e.png)
> 3. type in the cmd window`java -jar `
> 4. press Ctrl+V to paste in the path
> 5. Press enter

Unrecognized option: -jarD:\Minecraft\NC-Reactor-Generator\NC-Reactor-Generator-3.2.jar
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by zhangaoyu-me** [comment]
> > 1. Shift-right click the NC-Reactor-Generator jarfile
> > 2. Select `Copy as Path`
> >    ![image](https://user-images.githubusercontent.com/22590237/121688902-fa19de00-ca91-11eb-908f-03422e8cb60e.png)
> > 3. type in the cmd window`java -jar `
> > 4. press Ctrl+V to paste in the path
> > 5. Press enter
> 
> Unrecognized option: -jarD:\Minecraft\NC-Reactor-Generator\NC-Reactor-Generator-3.2.jar
> Error: Could not create the Java Virtual Machine.
> Error: A fatal exception has occurred. Program will exit.

Should - jar be replaced

**Comment by ThizThizzyDizzy** [comment]
Add a space between `-jar` and the path

**Comment by zhangaoyu-me** [comment]
> Add a space between `-jar` and the path

Version 3. X can't read the old ncPF file. How can I use the document built by the old version 2. X? Will version 2. X be updated

**Comment by zhangaoyu-me** [comment]
> Add a space between `-jar` and the path

An error will be reported as follows
C:\Users\zhang>java -jar "D:\Minecraft\NC-Reactor-Generator\NC-Reactor-Generator-3.2.jar"
Initializing...
OS: Windows
OS Architecture: x64
Checking Libraries...
Downloading lwjgl-assimp.jar...
Checking... 5% (1/19)
Failed to download library: lwjgl-assimp.jar!
Downloading lwjgl-glfw.jar...
Checking... 11% (2/19)
Failed to download library: lwjgl-glfw.jar!
Downloading lwjgl-openal.jar...
Checking... 16% (3/19)
Failed to download library: lwjgl-openal.jar!
Downloading lwjgl-opengl.jar...
Checking... 21% (4/19)
Failed to download library: lwjgl-opengl.jar!
Downloading lwjgl-stb.jar...
Checking... 26% (5/19)
Failed to download library: lwjgl-stb.jar!
Downloading lwjgl.jar...
Checking... 32% (6/19)
Failed to download library: lwjgl.jar!
Downloading lwjglx-debug-1.0.0.jar...
Checking... 37% (7/19)
Failed to download library: lwjglx-debug-1.0.0.jar!
Downloading lwjgl-openvr.jar...
Checking... 42% (8/19)
Failed to download library: lwjgl-openvr.jar!
Downloading lwjgl-nfd.jar...
Checking... 47% (9/19)
Failed to download library: lwjgl-nfd.jar!
Downloading lwjgl-assimp-natives-windows.jar...
Checking... 53% (10/19)
Failed to download library: lwjgl-assimp-natives-windows.jar!
Downloading lwjgl-glfw-natives-windows.jar...
Checking... 58% (11/19)
Failed to download library: lwjgl-glfw-natives-windows.jar!
Downloading lwjgl-natives-windows.jar...
Checking... 63% (12/19)
Failed to download library: lwjgl-natives-windows.jar!
Downloading lwjgl-openal-natives-windows.jar...
Checking... 68% (13/19)
Failed to download library: lwjgl-openal-natives-windows.jar!
Downloading lwjgl-opengl-natives-windows.jar...
Checking... 74% (14/19)
Failed to download library: lwjgl-opengl-natives-windows.jar!
Downloading lwjgl-stb-natives-windows.jar...
Checking... 79% (15/19)
Failed to download library: lwjgl-stb-natives-windows.jar!
Downloading lwjgl-openvr-natives-windows.jar...
Checking... 84% (16/19)
Failed to download library: lwjgl-openvr-natives-windows.jar!
Downloading lwjgl-nfd-natives-windows.jar...
Checking... 89% (17/19)
Failed to download library: lwjgl-nfd-natives-windows.jar!
Downloading SimpleLibraryPlus-1.5.jar...
Checking... 95% (18/19)
Failed to download library: SimpleLibraryPlus-1.5.jar!
Downloading joml-1.10.0.jar...
Checking... 100% (19/19)
Failed to download library: joml-1.10.0.jar!
Exception in thread "main" java.lang.NoClassDefFoundError: simplelibrary/opengl/Renderer2D
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at planner.Main.main(Main.java:80)
Caused by: java.lang.ClassNotFoundException: simplelibrary.opengl.Renderer2D
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 13 more

**Comment by ThizThizzyDizzy** [comment]
looks like it failed to download the libraries; I'm not sure what the problem is
> Version 3. X can't read the old ncPF file. How can I use the document built by the old version 2. X? Will version 2. X be updated

planner version 3.x can open all NCPF files from previous versions. Your file may be corrupted; try opening it in recovery mode (press Ctrl+Shift+R on the main menu before loading the file)

**Comment by zhangaoyu-me** [comment]
> looks like it failed to download the libraries; I'm not sure what the problem is
> 
> > Version 3. X can't read the old ncPF file. How can I use the document built by the old version 2. X? Will version 2. X be updated
> 
> planner version 3.x can open all NCPF files from previous versions. Your file may be corrupted; try opening it in recovery mode (press Ctrl+Shift+R on the main menu before loading the file)

So what is the link to download lib? Is it in the code? I try to download it manually. What content do I want to download

**Comment by zhangaoyu-me** [comment]
> looks like it failed to download the libraries; I'm not sure what the problem is
> 
> > Version 3. X can't read the old ncPF file. How can I use the document built by the old version 2. X? Will version 2. X be updated
> 
> planner version 3.x can open all NCPF files from previous versions. Your file may be corrupted; try opening it in recovery mode (press Ctrl+Shift+R on the main menu before loading the file)

Can I download lib manually? Where can I find the download link

**Comment by ThizThizzyDizzy** [comment]
the links to the libraries can be found in [Main.java](https://github.com/ThizThizzyDizzy/nc-reactor-generator/blob/923f996db4900a6213d4cfafe331e98e41e437dd/src/planner/Main.java), but I'll list them here:

[SimpleLibraryPlus-1.5.jar](https://github.com/ThizThizzyDizzy/SimpleLibraryPlus/releases/download/v1.5/SimpleLibraryPlus-1.5.jar)
[joml-1.10.0.jar](https://github.com/ThizThizzyDizzy/thizzyz-games-launcher/raw/master/libraries/lwjgl-3.2.3/jar/joml-1.10.0.jar)
[lwjgl-assimp.jar](https://github.com/ThizThizzyDizzy/thizzyz-games-launcher/raw/master/libraries/lwjgl-3.2.3/jar/lwjgl-assimp.jar)
[lwjgl-glfw.jar](https://github.com/ThizThizzyDizzy/thizzyz-games-launcher/raw/master/libraries/lwjgl-3.2.3/jar/lwjgl-glfw.jar)
[lwjgl-openal.jar](https://github.com/ThizThizzyDizzy/thizzyz-games-launcher/raw/master/libraries/lwjgl-3.2.3/jar/lwjgl-openal.jar)
[lwjgl-opengl.jar](https://github.com/ThizThizzyDizzy/thizzyz-games-launcher/raw/master/libraries/lwjgl-3.2.3/jar/lwjgl-opengl.jar)
[lwjgl-stb.jar](https://github.com/ThizThizzyDizzy/thizzyz-games-launcher/raw/master/libraries/lwjgl-3.2.3/jar/lwjgl-stb.jar)
[lwjgl.jar](https://github.com/ThizThizzyDizzy/thizzyz-games-launcher/raw/master/libraries/lwjgl-3.2.3/jar/lwjgl.jar)
[lwjglx-debug-1.0.0.jar](https://github.com/ThizThizzyDizzy/thizzyz-games-launcher/raw/master/libraries/lwjgl-3.2.3/jar/lwjglx-debug-1.0.0.jar)
[lwjgl-openvr.jar](https://github.com/ThizThizzyDizzy/thizzyz-games-launcher/raw/master/libraries/lwjgl-3.2.3/jar/lwjgl-openvr.jar)
[lwjgl-nfd.jar](https://github.com/ThizThizzyDizzy/thizzyz-games-launcher/raw/master/libraries/lwjgl-3.2.3/jar/lwjgl-nfd.jar)
(assuming 64 bit windows)
[lwjgl-assimp-natives-windows.jar](https://github.com/ThizThizzyDizzy/thizzyz-games-launcher/raw/master/libraries/lwjgl-3.2.3/native/windows/lwjgl-assimp-natives-windows.jar)
[lwjgl-glfw-natives-windows.jar](https://github.com/ThizThizzyDizzy/thizzyz-games-launcher/raw/master/libraries/lwjgl-3.2.3/native/windows/lwjgl-glfw-natives-windows.jar)
[lwjgl-natives-windows.jar](https://github.com/ThizThizzyDizzy/thizzyz-games-launcher/raw/master/libraries/lwjgl-3.2.3/native/windows/lwjgl-natives-windows.jar)
[lwjgl-openal-natives-windows.jar](https://github.com/ThizThizzyDizzy/thizzyz-games-launcher/raw/master/libraries/lwjgl-3.2.3/native/windows/lwjgl-openal-natives-windows.jar)
[lwjgl-opengl-natives-windows.jar](https://github.com/ThizThizzyDizzy/thizzyz-games-launcher/raw/master/libraries/lwjgl-3.2.3/native/windows/lwjgl-opengl-natives-windows.jar)
[lwjgl-stb-natives-windows.jar](https://github.com/ThizThizzyDizzy/thizzyz-games-launcher/raw/master/libraries/lwjgl-3.2.3/native/windows/lwjgl-stb-natives-windows.jar)
[lwjgl-openvr-natives-windows.jar](https://github.com/ThizThizzyDizzy/thizzyz-games-launcher/raw/master/libraries/lwjgl-3.2.3/native/windows/lwjgl-openvr-natives-windows.jar)
[lwjgl-nfd-natives-windows.jar](https://github.com/ThizThizzyDizzy/thizzyz-games-launcher/raw/master/libraries/lwjgl-3.2.3/native/windows/lwjgl-nfd-natives-windows.jar)

Those files should be put into a folder called `libraries`, which should be in the same folder as the planner jarfile (it may have created the libraries folder already)
The files should not be renamed (their names should match what is seen above)

**Comment by zhangaoyu-me** [comment]
> the links to the libraries can be found in [Main.java](https://github.com/ThizThizzyDizzy/nc-reactor-generator/blob/923f996db4900a6213d4cfafe331e98e41e437dd/src/planner/Main.java), but I'll list them here:
> 
> [SimpleLibraryPlus-1.5.jar](https://github.com/ThizThizzyDizzy/SimpleLibraryPlus/releases/download/v1.5/SimpleLibraryPlus-1.5.jar)
> [joml-1.10.0.jar](https://github.com/ThizThizzyDizzy/thizzyz-games-launcher/raw/master/libraries/lwjgl-3.2.3/jar/joml-1.10.0.jar)
> [lwjgl-assimp.jar](https://github.com/ThizThizzyDizzy/thizzyz-games-launcher/raw/master/libraries/lwjgl-3.2.3/jar/lwjgl-assimp.jar)
> [lwjgl-glfw.jar](https://github.com/ThizThizzyDizzy/thizzyz-games-launcher/raw/master/libraries/lwjgl-3.2.3/jar/lwjgl-glfw.jar)
> [lwjgl-openal.jar](https://github.com/ThizThizzyDizzy/thizzyz-games-launcher/raw/master/libraries/lwjgl-3.2.3/jar/lwjgl-openal.jar)
> [lwjgl-opengl.jar](https://github.com/ThizThizzyDizzy/thizzyz-games-launcher/raw/master/libraries/lwjgl-3.2.3/jar/lwjgl-opengl.jar)
> [lwjgl-stb.jar](https://github.com/ThizThizzyDizzy/thizzyz-games-launcher/raw/master/libraries/lwjgl-3.2.3/jar/lwjgl-stb.jar)
> [lwjgl.jar](https://github.com/ThizThizzyDizzy/thizzyz-games-launcher/raw/master/libraries/lwjgl-3.2.3/jar/lwjgl.jar)
> [lwjglx-debug-1.0.0.jar](https://github.com/ThizThizzyDizzy/thizzyz-games-launcher/raw/master/libraries/lwjgl-3.2.3/jar/lwjglx-debug-1.0.0.jar)
> [lwjgl-openvr.jar](https://github.com/ThizThizzyDizzy/thizzyz-games-launcher/raw/master/libraries/lwjgl-3.2.3/jar/lwjgl-openvr.jar)
> [lwjgl-nfd.jar](https://github.com/ThizThizzyDizzy/thizzyz-games-launcher/raw/master/libraries/lwjgl-3.2.3/jar/lwjgl-nfd.jar)
> (assuming 64 bit windows)
> [lwjgl-assimp-natives-windows.jar](https://github.com/ThizThizzyDizzy/thizzyz-games-launcher/raw/master/libraries/lwjgl-3.2.3/native/windows/lwjgl-assimp-natives-windows.jar)
> [lwjgl-glfw-natives-windows.jar](https://github.com/ThizThizzyDizzy/thizzyz-games-launcher/raw/master/libraries/lwjgl-3.2.3/native/windows/lwjgl-glfw-natives-windows.jar)
> [lwjgl-natives-windows.jar](https://github.com/ThizThizzyDizzy/thizzyz-games-launcher/raw/master/libraries/lwjgl-3.2.3/native/windows/lwjgl-natives-windows.jar)
> [lwjgl-openal-natives-windows.jar](https://github.com/ThizThizzyDizzy/thizzyz-games-launcher/raw/master/libraries/lwjgl-3.2.3/native/windows/lwjgl-openal-natives-windows.jar)
> [lwjgl-opengl-natives-windows.jar](https://github.com/ThizThizzyDizzy/thizzyz-games-launcher/raw/master/libraries/lwjgl-3.2.3/native/windows/lwjgl-opengl-natives-windows.jar)
> [lwjgl-stb-natives-windows.jar](https://github.com/ThizThizzyDizzy/thizzyz-games-launcher/raw/master/libraries/lwjgl-3.2.3/native/windows/lwjgl-stb-natives-windows.jar)
> [lwjgl-openvr-natives-windows.jar](https://github.com/ThizThizzyDizzy/thizzyz-games-launcher/raw/master/libraries/lwjgl-3.2.3/native/windows/lwjgl-openvr-natives-windows.jar)
> [lwjgl-nfd-natives-windows.jar](https://github.com/ThizThizzyDizzy/thizzyz-games-launcher/raw/master/libraries/lwjgl-3.2.3/native/windows/lwjgl-nfd-natives-windows.jar)
> 
> Those files should be put into a folder called `libraries`, which should be in the same folder as the planner jarfile (it may have created the libraries folder already)
> The files should not be renamed (their names should match what is seen above)

I can open it. Thank you so much

Support your work
