### ISSUE TITLE
Suggestion: Auto Generation in the metadata what Planner version was used

### ISSUE THREAD

**Issue by Thalzamar** [ThizThizzyDizzy/nc-reactor-generator#55]
might be helpful if the .ncpf file is changed again and the builder hasn't catched up yet to it 
or for other reasons

**Comment by ThizThizzyDizzy** [comment]
NCPF has its own version number that keeps track of changes to the NCPF format

**Comment by Thalzamar** [comment]
i mean the metadata that we people see that in the .png export we can see the planner version as well as the NCO version
