### ISSUE TITLE
Turbine planner leaks VRAM

### ISSUE THREAD

**Issue by h4ilst0rm** [ThizThizzyDizzy/nc-reactor-generator#58]
Turbine planner with NCOUTO leaks VRAM in spectacular fashion which either makes the system unresponsive untill it clears or it might just crash the display driver altogether. Starts by hovering over coils in the part picker or maybe chaging the search terms, and gets worse over time, maybe related to the tooltips?
![image](https://user-images.githubusercontent.com/59488828/124029684-10b2b580-d9fe-11eb-8c97-3f57fd2063c1.png)
![image](https://user-images.githubusercontent.com/59488828/124029812-350e9200-d9fe-11eb-8b5e-8927de680f7b.png)

**Comment by h4ilst0rm** [comment]
[Error Wed Jun 30 23-51-25 EEST 2021.log](https://github.com/ThizThizzyDizzy/nc-reactor-generator/files/6743968/Error.Wed.Jun.30.23-51-25.EEST.2021.log)

**Comment by ThizThizzyDizzy** [comment]
(Dev build) turbine expansion graph no longer uses a framebuffer

**Comment by ThizThizzyDizzy** [comment]
Fixed in v4.0
