### ISSUE TITLE
[Bug] Coil validation - Inconsistency with NC mechanics

### ISSUE THREAD

**Issue by ThePoleThatFishes** [ThizThizzyDizzy/nc-reactor-generator#60]
In NC, if coils are placed that require (only) casing, are invalid if there is no path to the bearing, that is not reflected in the plannerator.

**Comment by ThizThizzyDizzy** [comment]
Is this a special rule for coils that only depend on a casing, or is it a more general rule?
Also, which blocks can be used as a path to the bearing?

**Comment by ThePoleThatFishes** [comment]
I would say it's more of a general rule, that has just become apparent with casing-only coils. (Possibly applies to other coils that may not require other coils or connectors/bearings to be valid)

Blocks that count as path to bearing are other valid coils and connectors.

**Comment by ThizThizzyDizzy** [comment]
Wouldn’t that make this valid though, since the coils are connected to the
bearing via a connector?
https://media.discordapp.net/attachments/736405649675518053/862431881210495016/unknown.png

...Or should the connector be invalid since the coils depend on it

**Comment by ThePoleThatFishes** [comment]
That is invalid, as the corner coils are all invalid (no connection to bearing)
One coil being invalid makes the connectors invalid too, so everything invalidates.
