### ISSUE TITLE
[Bug] Odd crash happening during heatsink placement

### ISSUE THREAD

**Issue by ThePoleThatFishes** [ThizThizzyDizzy/nc-reactor-generator#62]
Placed a custom coil with a shield + casing rule and planner just crashed...
[crash-Sun Jul 18 23-48-54 EEST 2021.txt](https://github.com/ThizThizzyDizzy/nc-reactor-generator/files/6836938/crash-Sun.Jul.18.23-48-54.EEST.2021.txt)

**Comment by ThizThizzyDizzy** [comment]
I'm assuming you mean a custom heatsink, since you were editing an SFR

I'm unable to reproduce the issue; Can you provide the configuration you used?

**Comment by ThePoleThatFishes** [comment]
Here's the config, it's default with confectionery addon plus extra heatsinks I was testing (had to upload as zip cause github)
[config_new.zip](https://github.com/ThizThizzyDizzy/nc-reactor-generator/files/6838150/config_new.zip)

**Comment by ThizThizzyDizzy** [comment]
I wasn't able to reproduce the crash, and I'm not sure what's could have caused it

@Lymia Do you have any idea what's happening? It seems to be mixing up SFRs and MSRs

**Comment by Lymia** [comment]
It looks like a MSR placement rule (or a MSR block) somehow got into a SFR... Hrm. Probably a simple typo somewhere. @.@

**Comment by ThePoleThatFishes** [comment]
I can't reproduce either for some reason, it just happened once and that was it :/

**Comment by ThePoleThatFishes** [comment]
Okay yet another crash similar to before, now it's a turbine block being casted to MSR...?!
[crash-Tue Jul 20 11-42-12 EEST 2021.txt](https://github.com/ThizThizzyDizzy/nc-reactor-generator/files/6846794/crash-Tue.Jul.20.11-42-12.EEST.2021.txt)
EDIT: I found out why: I selected "Any conductor" as the validation rule for a coil and it crashed, disregard this report

**Comment by ThePoleThatFishes** [comment]
I think I know why the crash happens:
When you create a component for the first time, you get this menu:
![img](https://cdn.discordapp.com/attachments/745257089357709402/866965869627834388/unknown.png)
It picks from the list of MSR components at the start, then uses the correct components.

This seems to go deeper.
When creating a new heatsink, you get as placement rules the groups of components in MSRs and then SFR components.
When creating a new heater, you get as placement rules the groups of components in MSRs, and then the SFR components.
When creating a new coil, you get as placement rules the groups of components in MSRs, and then the turbine components.

**Comment by ThizThizzyDizzy** [comment]
Oh, interesting

That also makes sense why it didn't crash for me, since that's probably fixed upon save/load
