### ISSUE TITLE
[Bug] Coil suggestors erroring

### ISSUE THREAD

**Issue by ThePoleThatFishes** [ThizThizzyDizzy/nc-reactor-generator#66]
Coil suggestors break yet again :(
[Error Mon Sep 13 23-44-29 EEST 2021.log](https://github.com/ThizThizzyDizzy/nc-reactor-generator/files/7157303/Error.Mon.Sep.13.23-44-29.EEST.2021.log)
Addons: QMD, NCOUTO, MHS, MRF and Confectionery

**Comment by ThizThizzyDizzy** [comment]
Whoops, forgot groups were used for that lol

**Comment by ThizThizzyDizzy** [comment]
Probably fixed this ages ago and forgot to close it; Coil suggestors work properly in v3.5.1
