### ISSUE TITLE
[BUG] Tooltips stay black and white in disco theme

### ISSUE THREAD

**Issue by joendter** [ThizThizzyDizzy/nc-reactor-generator#70]
![grafik](https://user-images.githubusercontent.com/71767955/142776312-7df95fa6-f078-4873-9d53-77eee7fe6830.png)

**Comment by ThizThizzyDizzy** [comment]
I actually noticed this yesterday; tooltip colors aren't adjusted by themes, and are locked to solid black & white, rather than the normal off-white and off-black colors

**Comment by ThizThizzyDizzy** [comment]
Added in v4.0
