### ISSUE TITLE
[BUG] Filename of automatically updated version differs from filename of manually downloaded one

### ISSUE THREAD

**Issue by joendter** [ThizThizzyDizzy/nc-reactor-generator#73]
The filename of my automatically updated version is "Nuclearcraft Reactor Generator 3.5.1.jar".
The filename of the manually downloaded one is "NC-Reactor-Generator-3.5.1.jar".
I don't see any reason why this should be.

**Comment by ThizThizzyDizzy** [comment]
Unable to reproduce with v3.5 -> v3.5.1

**Comment by joendter** [comment]
i also can't reproduce it with 3.5 -> 3.5.1

**Comment by joendter** [comment]
Though i can reproduce it with 2.15.5 -> 3.5.1 so it already seems to be fixed in the newer versions
