### ISSUE TITLE
Neutron sources are not properly saved to Hellrage JSON

### ISSUE THREAD

**Issue by joendter** [ThizThizzyDizzy/nc-reactor-generator#75]
Even though .json is depreciated it is i think the easiest way to use the nuclearcraft reactor builder. But with the current export implementation the casing is completely ignored. I would like if the information which cells are primed was exported as well.

**Comment by ThizThizzyDizzy** [comment]
Looks like it's just saved with the wrong name (includes " Neutron Source"), though there also may be an issue in the Hellrage JSON reader

**Comment by joendter** [comment]
i tried opening it with an older version of ur planner and it didn't show the priming as well

**Comment by ThizThizzyDizzy** [comment]
Fixed in v4.0
