### ISSUE TITLE
[BUG] Search bar for reactor components gets cleared after using pick block

### ISSUE THREAD

**Issue by joendter** [ThizThizzyDizzy/nc-reactor-generator#77]
Even though I can't find the pipette in the toolbar which confuses me, 3rd mousebutton works for me as one.
Before i use it i have -port in the component search bar:
![image](https://user-images.githubusercontent.com/71767955/145724293-9f4c653a-8776-48b6-bcdc-37460f1d064c.png)
After using it the "-port" is removed:
![image](https://user-images.githubusercontent.com/71767955/145724306-5fd4e57c-b8b0-4b51-a905-77a3cac5a84e.png)

**Comment by ThizThizzyDizzy** [comment]
Added in v4.0
