### ISSUE TITLE
Invalid MSR Moderator Lines

### ISSUE THREAD

**Issue by Thalzamar** [ThizThizzyDizzy/nc-reactor-generator#8]
tried a Design from Lach
it says for eg. in Layer 1 invalod Moderator in the Heater lines between the cell's
[F4LEU-235_7_x_5_x_5.zip](https://github.com/ThizThizzyDizzy/nc-reactor-generator/files/4872244/F4LEU-235_7_x_5_x_5.zip)

ingame stats:
it's missing over 1000 Heat in the Planner compared to ingame
![grafik](https://user-images.githubusercontent.com/48890032/86507915-0acec800-bddc-11ea-9eba-0f2634d0968d.png)

**Comment by ThizThizzyDizzy** [comment]
As far as I'm aware, heatsinks don't form moderator lines on their own, and require at least one moderator in the line
![image](https://user-images.githubusercontent.com/22590237/86513068-1d91ce80-bdd5-11ea-9e64-746a67422001.png)
(lower line invalid, upper line valid)

However, if I account for that, it brings the planner's heat up to positive ~150 H/t

**Comment by ThizThizzyDizzy** [comment]
Released a patch to fix the zero-flux moderator lines.
Is the screenshot up to date with current fuel and heater values?
