### ISSUE TITLE
[SUGGESTION] Make 3D view in editor remember its state

### ISSUE THREAD

**Issue by joendter** [ThizThizzyDizzy/nc-reactor-generator#81]
I really like the 3D preview in the plannerator but i always find it kinda cumbersome that you have to activate it every time you restart the plannerator. I would like if there was a setting to toggle it on by default.

**Comment by ThizThizzyDizzy** [comment]
3D view will be kept off by default, as it serves no functional purpose and can be a significant performance drain when on.
However, I can certainly make it stay on once you turn it on
