### ISSUE TITLE
Fuel Ports cannot be relocated with Auto Build Casings option enabled

### ISSUE THREAD

**Issue by Spikey5** [ThizThizzyDizzy/nc-reactor-generator#89]
I tried to move the fuel ports from the generated location with the move tool but they won't move. and they can't be deleted (fair enough).
Disabling the Auto Build Casings option let me move them as expected. Didn't occur with reactor vents, they could be freely relocated.

**Comment by ThizThizzyDizzy** [comment]
You should be able to move a fuel port by placing a new one, then removing the old one
The move tool should work as well, did you select it first?

**Comment by Spikey5** [comment]
Yep, I had the ports selected before I moved them. I was unable to place a new fuel port
