### ISSUE TITLE
Request: Make JSON-Export differentiate between Active/Passive cooling for display in NC Reactor Planner

### ISSUE THREAD

**Issue by Shad0wlife** [ThizThizzyDizzy/nc-reactor-generator#9]
Currently, when exporting a Reactor layout (for old Nuclearcraft) to JSON and then displaying it in the NC Reactor planner, all coolers are passive. Obviously, switching all of them to active won't work due to the neighbor-rules. I would really like to get an overview of this information, but cannot really export it it seems.

Would it be possible to relay this information into the JSON?

The Reactor Planner's format for marking active coolers is to just add an "Active " in front of the Cooler group name (eg. "Cryotheum" -> "Active Cryotheum". If this change would lead to incompatibilities with other software that could not parse this information, maybe it would be possible to set a checkbox for it in the Export dialog?

EDIT: If this is a user error on my side please close. I just realized that the layout was actually entirely passively cooled, though that again made me curious whether active cooling would not allow for more reactor chambers.

**Comment by ThizThizzyDizzy** [comment]
The generator doesn’t use active coolers at all
The new one will, but it’s not done yet
