### ISSUE TITLE
Undo/Redo Button Not Working Properly

### ISSUE THREAD

**Issue by player19375** [ThizThizzyDizzy/nc-reactor-generator#92]
The undo/redo functions aren't working properly as of now. The removal of components is not working properly. When I undo placing heat sinks, only around half of them are removed, and when I press the undo button more, a few other heat sinks get removed. When I spam the redo button, I can get back to the position before undoing. I have not spotted any trend other than that the undo button is never working properly. 
P. S. I redownloaded the planner to ensure that I did not mess up when the planner was updated.

**Comment by ThizThizzyDizzy** [comment]
So if I'm understanding this correctly, it takes multiple undos to undo a single action, yes?
What actions are you trying to undo? Which tools does this affect?

**Comment by player19375** [comment]
I'm mostly using box tool, but I use pencil tool occasionally. 
When I press the undo button, the undo action is not done properly. After I place lots of heat sinks with control + the box tool and undo the action, only part of the heat sinks are removed, and some more heat sinks get removed (or some cell placement/removal are reverted) when I press the undo button again. I can never undo the entire action (of placing lapis heat sinks in all valid spots, for instance). 
From my experience, it affects placement of all blocks, so I **think** it is an issue related to saving the action.
